### ISSUE TITLE
RR.prototype._domainToName

### ISSUE THREAD

**Issue by Zadagu** [damoun/dnsserver.js#2]
Hello, i maybe found a bug, or i just doing something wrong.
in RR.prototype._domainToName the size of the buffer name can't be valid.
I thought the buffer is build like folloing:
1 Byte: length of label1
x Byte: label1
1 Byte: length of labelX
x Byte: labelX
1 Byte: 0
so i think in RR.js on line 26 must look like that:
var name = new Buffer(domain.length + 1 + labels.length);

**Comment by damoun** [comment]
HI @Zadagu 

The domain length is equal to each label + 1 byte so the buffer size is right.

example: google.com.
labels = ["google", "com", ""]
buffer = "6google3com0"

Because there are an empty element in the labels array, the 0 byte is written in the for statement, so I have to remove the line 34 to avoid a buffer overflow.
